global:
  scrape_interval: 5s # Server 抓取頻率
  external_labels:
    monitor: "demo-monitor"

rule_files:
  - /etc/prometheus/alert_rules.yaml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'api_monitor'
    scrape_interval: 5s
    static_configs:
        - targets: ['web:5000']